import * as fs from "node:fs/promises";
import * as path from "node:path";
import type { AgentRequest, AgentResult, IAgentExecutor, Plan, PlanStep } from "@orchlet/core";

export class MockAgentProvider implements IAgentExecutor {
  readonly harnessName = "mock";

  async execute(request: AgentRequest): Promise<AgentResult> {
    const startTime = Date.now();
    const changedFiles: string[] = [];

    if (request.role === "executor") {
      // Simulate real code generation in the worktree
      const srcDir = path.join(request.worktreePath, "src");
      await fs.mkdir(srcDir, { recursive: true });
      const targetFile = path.join(srcDir, "utils.ts");
      await fs.writeFile(
        targetFile,
        `// Generated by Orchlet executor (${request.selectedModel.modelId})\nexport function formatTimestamp(date: Date = new Date()): string {\n  return date.toISOString();\n}\n`,
        "utf-8",
      );
      changedFiles.push("src/utils.ts");
    } else if (request.role === "repairer") {
      // Apply repair to addressing findings
      const srcDir = path.join(request.worktreePath, "src");
      await fs.mkdir(srcDir, { recursive: true });
      const testFile = path.join(srcDir, "utils.test.ts");
      await fs.writeFile(
        testFile,
        `// Test file generated by Orchlet repairer (${request.selectedModel.modelId})\nimport { formatTimestamp } from "./utils.js";\nif (!formatTimestamp()) process.exit(1);\n`,
        "utf-8",
      );
      changedFiles.push("src/utils.test.ts");
    }

    return {
      success: true,
      textResponse: `Mock agent executed role ${request.role} successfully`,
      changedFiles,
      usage: {
        promptTokens: 120,
        completionTokens: 85,
        totalTokens: 205,
        costEstimateUsd: 0.0004,
      },
      modelUsed: request.selectedModel.modelId,
      providerUsed: request.selectedModel.providerId,
      durationMs: Date.now() - startTime,
    };
  }

  async generatePlan(intent: string, taskId: string): Promise<Plan> {
    const steps: PlanStep[] = [
      {
        id: "step_1",
        order: 1,
        title: "Analyze workspace and requirements",
        description: `Analyze scope for: ${intent}`,
        status: "COMPLETED",
      },
      {
        id: "step_2",
        order: 2,
        title: "Implement code changes",
        description: "Write targeted code modifications in isolated worktree",
        status: "PENDING",
      },
      {
        id: "step_3",
        order: 3,
        title: "Verify tests and build",
        description: "Run automated test suites and linters",
        status: "PENDING",
      },
    ];

    return {
      id: `plan_${taskId}`,
      taskId,
      title: `Execution Plan: ${intent.slice(0, 50)}`,
      summary: `Automated plan generated for: ${intent}`,
      steps,
      architectVerdict: "APPROVED",
      architectNotes: "Architect verified plan adheres to safety guidelines and monorepo boundaries.",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  }
}

export const mockAgentProvider = new MockAgentProvider();
